### ISSUE TITLE
CodeNotFoundError when attempting to receive

### ISSUE THREAD

**Issue by alassek** [KuroLabs/Airshare#14]
This tool looks really neat! I've been looking for something like this for a while. I'm having some difficulty getting started though. Something seems wrong with the name resolution on my machine but Avahi is installed and working.

[![asciicast](https://asciinema.org/a/5FiaTbPtGJ0g1BYywotW0ZlSQ.svg)](https://asciinema.org/a/5FiaTbPtGJ0g1BYywotW0ZlSQ)

```
Traceback (most recent call last):
  File "/home/adam/.local/bin/airshare", line 11, in <module>
    sys.exit(main())
  File "/home/adam/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/adam/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/adam/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adam/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/adam/.local/lib/python3.6/site-packages/airshare/cli.py", line 83, in main
    receive(code=code)
  File "/home/adam/.local/lib/python3.6/site-packages/airshare/receiver.py", line 102, in receive
    raise CodeNotFoundError(code)
airshare.exception.CodeNotFoundError: CodeNotFoundError: The Airshare `Psykosis.local` was not found!
```

OS: Ubuntu 18.04 x86_64
Kernel: 4.15.0-101-generic

Do you have any thoughts about whats going wrong?

**Comment by mohanpierce99** [comment]
Ah , So to send a file you should use airshare pysokosis a.mp4 but to receive one  in another pc in the same network all one has to do airshare pysokosis - so that's what you did you received without sending a file in the first place  hence airshare says not found :)

**Comment by mohanpierce99** [comment]
I'm closing this issue, take a look at the demo and the usage if you have more issues regarding this. Cheers!

**Comment by alassek** [comment]
Ah, so sending from iOS is impossible, then?

**Comment by mohanpierce99** [comment]
> Ah, so sending from iOS is impossible, then?

It's possible! In your PC (mac or windows or Linux) do 
```bash
airshare john -u 
```
 from iOS -  go to your browser and type john.local and upload the file you want.
